language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Additional components
    - extra-google-google_play_services
    #- addon-google_apis-google-19

    # Specify at least one system image, if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

  licenses:
    - '.+'

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/2.14
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
script:
    bash gradlew test